// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Persistence;
using Domain.Entities;

namespace Persistence.Seed
{
     public class SubjectDbInitializer
        {
            public static void Seed(ModelBuilder modelBuilder)
            {
                modelBuilder.Entity<Subject>().HasData(
                new Subject { SubjectId = new Guid(), Title = "Math", Credits = 8},
                new Subject { SubjectId = new Guid(), Title = "Chemistry", Credits = 10 }
                );
            }
        }
}
